function [pac, tf, a_events, mod_sig] = otc(x, ...
    f_hi, f_step, fs, w, event_prc, t_modsig, t_buffer)
setpypath
[pac, tf, a_events, mod_sig] = py.pac.otc(x, ...
    f_hi, f_step, fs, w, event_prc, t_modsig, t_buffer);